zpravodaj:
    name: Zpravodaj
    singular_name: Článek
    slug: blog
    singular_slug: clanek
    description: |
      Zpravodaj je informačním kanálem pavilonu, jsou zde publikovány všechny možné informace o pavilonu.
    fields:
        title_cs:
            type: text
            class: large
            group: Texty
            label: Název (CS)
        slug:
            type: slug
            uses: title_cs
        featured:
             type: checkbox
             label: Zvýraznit zprávu
             default: unchecked
        text_cs:
            type: html
            height: 300px
            label: Text (CS)
        title_en:
            type: text
            class: large
            group: (EN)
            label: Název (EN)
        text_en:
            type: html
            height: 300px
            label: Text (EN)
        image:
            type: image
            group: Média
            extensions: [ gif, jpg, png, jpeg ]
            label: náhledový obrázek
            postfix: minimální velikost 620x465px | Název souboru bez českých znaků a mezer! Povolené typy souborů: gif, png, jpg, jpeg
        video:
            type: video
        imagelist:
            type: imagelist
            extensions: [ gif, jpg, png, jpeg ]
            label: galerie
            postfix: ideální velikost 1280x960 | minimální velikost 1024x768px | název souboru bez českých znaků a mezer! Povolené typy souborů: gif, png, jpg, jpeg
        filelist:
            type: filelist
            group: Soubory
            extensions: [ doc, docx, pdf, xls, xlsx, ods, odt ]
            label: Spobory(y) ke stažení
    relations:
        zpravodaj:
            multiple: true
            label: Vyberte článek
            order: -id
            format: "{{ item.title|escape }} <span>(№ {{ item.id }})</span>"
    taxonomy: [ kategorie ]
    show_on_dashboard: true
    default_status: concept
    searchable: true
    record_template: entry.twig
    listing_template: zpravodaj.twig
    listing_records: 14
    recordsperpage: 14
    sort: -datepublish
    icon: cubes
    icon_singular: cube

sponzori:
    name: Sponzori
    singular_name: Sponzor
    description: |
    Seznam partnerů pavilonu. Třídí se pomocí štítků: Zlatý, Stříbrný, Bronzový
    fields:
        nazev_cs:
            type: text
            class: large
            group: Obsah
        slug:
            type: slug
            uses: nazev_cs
        popis_cs:
            type: textarea
            postfix: Velmi krátký popis partnera - objeví se pod logem.
        odkaz:
            type: text
            class: large
            postfix: Vlozte webovou adresu partnera
        logo:
            type: image
            extensions: [ gif, png, tif ]
            postfix: UPOZORNĚNÍ: Upravte logo aby mělo průhledné pozadí !!!  Logo musí být vystředěné na plátně o velikosti 280x210 !!!  
        nazev_en:
            type: text
            class: large
            group: (EN)
        popis_en:
            type: textarea
            postfix: Velmi krátký popis partnera - objeví se pod logem.
    relations:
        zpravodaj:
            multiple: false
            label: Vyberte článek
            order: -id
            format: "{{ item.title|escape }} <span>(№ {{ item.id }})</span>"
    taxonomy: [ stitky ]
    default_status: published

odkazy:
    name: Odkazy
    singular_name: Odkaz
    fields:
        nazev_cs:
            type: text
            class: large
            group: Obsah
        popis_cs:
            type: text
            class: large
            label: Popisek
            postfix: velmi krátký údaj např. datum publikace, název periodika, odděleno čárkami
        adresa:
            type: text
            postfix: Adresa URL
        nazev_en:
            type: text
            class: large
            group: (EN)
        popis_en:
            type: text
            class: large
            label: Popisek (EN)
            postfix: velmi krátký údaj např. datum publikace, název periodika, odděleno čárkami
        slug:
            type: slug
            uses: nazev_cs
    taxonomy: [ rozcestnik ]

historie:
    name: Historie
    singular_name: historie
    description: |
      Historie pavilonů EXPO
    fields:
        title_cs:
            type: text
            class: large
            group: Texty (CS)
            label: Název
        slug:
            type: slug
            uses: title_cs
        rok:
            type: text
            label: Rok konání
        mesto_cs:
            type: text
            label: Město
        tema_cs:
            type: text
            label: Téma výstavy
        cztema_cs:
            type: text
            label: Téma české expozice
        autor-pavilonu:
            type: text
            label: Autor(ři) Pavilonu
            postfix: Autory případně oddělte čárkou
        autor-expozice:
            type: text
            label: Autor(ři) expozice
            postfix: Autory případně oddělte čárkou
        text_cs:
            type: html
            height: 500px
            label: Text
        title_en:
            type: text
            class: large
            group: (EN)
            label: Název (EN)
        mesto_en:
            type: text
            label: Město (EN)
        tema_en:
            type: text
            label: Téma výstavy (EN)
        cztema_en:
            type: text
            label: Téma české expozice (EN)
        text_en:
            type: html
            height: 500px
            label: Text (EN)
        nahled:
            type: image
            group: media
        imagelist:
            type: imagelist
            extensions: [ gif, jpg, png, jpeg ]
            label: galerie
            postfix: ideální velikost 1280x960 | minimální velikost 1024x768px | název souboru bez českých znaků a mezer! Povolené typy souborů: gif, png, jpg, jpeg
    record_template: entry.twig
    listing_template: historie.twig
    listing_records: 60
    default_status: publish
    sort: -datepublish
    recordsperpage: 60
    show_on_dashboard: false


bloky:
    name: Bloky
    singular_name: Blok
    description: |
      Bloky slouží k uchování částí statických onepagerů.  
    fields:
        title_cs:
            type: text
            class: large
            group: Texty
            label: Nadpis
        slug:
            type: slug
            uses: title_cs
        body_cs:
            type: textarea
            height: 300px
            label: Text
        title_en:
            type: text
            class: large
            group: (EN)
            label: Nadpis (EN)    
        body_en:
            type: textarea
            height: 300px
            label: Text (EN)
    relations:
        modaly:
            multiple: false
            label: Vyberte obsah s detailním popisem
            order: -id
            format: "{{ item.title|escape }} <span>(№ {{ item.id }})</span>"
    taxonomy: [ statiky ]
    show_on_dashboard: false
    default_status: publish
    searchable: false
    recordsperpage: 100

modaly:
    name: Modaly
    singular_name: Modal
    description: |
      Modaly se starají o obsah vyskakovacích okýnek,
    fields:
        title_cs:
            type: text
            class: large
            group: Texty
        slug:
            type: slug
            uses: title_cs
        body_cs:
            type: html
            height: 300px
        image:
            type: image
        title_en:
            type: text
            class: large
            group: (EN)
        body_en:
            type: html
            height: 300px
    taxonomy: [ statiky ]
    show_on_dashboard: false
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    recordsperpage: 10


Numbers:
    name: Čísla
    singular_name: číslo
    fields:
        title:
            type: text
            class: large
            label: Název proměnné
        slug:
            type: slug
        integerfield:
             type: integer
             label: Hodnota
    show_on_dashboard: false


ProgressBar:
    name: Časová osa
    singular_name: Bod časové osy
    fields:
        title_cs:
            type: text
            class: large
            label: Popis bodu časové osy
            group: Bod na časové ose
        slug:
            type: slug
        poloha:
            type: date
        korekce:
            type: integer
            label: Korekce polohy na Časové ose    
        image:
            type: image
            label: ikona
            extensions: [ gif, png, svg ]
            postfix: ikona 60x60px, povolené formáty png, gif, svg
        title_en:
            type: text
            class: large
            label: Popis bodu časové osy (EN)
            group: (EN)
    relations:
        zpravodaj:
            multiple: false
            label: Vyberte článek
            order: -id
            format: "{{ item.title|escape }} <span>(№ {{ item.id }})</span>"
    show_on_dashboard: false
    default_status: publish
    recordsperpage: 100


Strany:
    name: Pages
    singular_name: Page
    description: |
      Slouží k prezentaci onepagerů (pavilon).
    fields:
        title_cs:
            type: text
            class: large
            group: Obsah
        title_en:
            type: text
            class: large
        slug:
            type: slug
            uses: title_cs
        template:
            type: templateselect
            filter: '*.twig'
    recordsperpage: 100
    show_on_dashboard: false

# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes

# Pages can be used for the more 'static' pages on your site. Things like
# 'about us', 'contact' or a 'disclaimer'. This content-type has a 'templateselect'
# field, which allows you to override the record_template setting for an
# individual page.
# The taxonomy for this contenttype is defined as 'chapters', which is a so-called
# "grouping" taxonomy. This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

# pages:
#     name: Pages
#     singular_name: Page
#     description: |
#       The **Pages** contentype can be used for the more 'static' pages on your site. Things like
#       _'about us'_, _'contact'_ or a _'disclaimer'_.  
#       To change the fields that are in this contenttype, edit the file `contenttypes.yml` in the
#       folder `app/config/`, using the editor of your choice, or by going to 'Configuration' »
#       'Contenttypes' in the menu on the left.
#     fields:
#         title:
#             type: text
#             class: large
#             group: content
#         slug:
#             type: slug
#             uses: title
#         image:
#             type: image
#         teaser:
#             type: html
#             height: 150px
#         body:
#             type: html
#             height: 300px
#         template:
#             type: templateselect
#             filter: '*.twig'
#     taxonomy: [ chapters ]
#     recordsperpage: 100


# Entries can be used for things like 'news' or 'blogpostings'. They have a 'teaser',
# which can be used for a short blurb on listing-pages, allowing visitors to
# click-through to the rest of the entry. It also has fields for an image and an
# optional video.
# A relation is defined to the pages contenttype. This way you can refer to a page
# from your news-item.
# This contenttype defines 'categories' and 'tags' as taxonomies, allowing the
# editor to use both to categorize a specific entry.
# The 'sort' is set to "datepublish DESC", which means that newer entries will
# show above older entries.

# entries:
#     name: Entries
#     singular_name: Entry
#     description: |
#       The **Entries** contentype can be used for things like _'news'_ or _'blogpostings'_. They
#       have a teaser, which can be used for a short blurb on listing-pages, allowing visitors to
#       click-through to the rest of the entry. It also has fields for an image and an optional video.  
#       To change the fields that are in this contenttype, edit the file `contenttypes.yml` in the
#       folder `app/config/`, using the editor of your choice, or by going to 'Configuration' »
#       'Contenttypes' in the menu on the left.
#     fields:
#         title:
#             type: text
#             class: large
#             group: content
#         slug:
#             type: slug
#             uses: title
#         teaser:
#             type: html
#             height: 150px
#         body:
#             type: html
#             height: 300px
#         image:
#             type: image
#             group: media
#         video:
#             type: video
#     relations:
#         pages:
#           multiple: false
#           order: title
#           label: Select a page
#     taxonomy: [ categories, tags ]
#     record_template: entry.twig
#     listing_template: listing.twig
#     listing_records: 10
#     default_status: publish
#     sort: -datepublish
#     recordsperpage: 10

# The 'Showcases' is not particularly useful in most cases, but it does a good
# job of showcasing most of the available fieldtypes. Feel free to delete it, or
# copy some fields to your own contenttypes.
# Since no templates are defined for this contenttype, the default record_template,
# listing_template, and related settings are used from config.yml

# showcases:
#     name: Showcases
#     slug: showcases
#     singular_name: Showcase
#     singular_slug: showcase
#     description: |
#       The **Showcases** contentype is used to show all of the available common field types.
#       In practice, its uses are limited, but be sure to take a look to see which fields are
#       available for use.  
#       To change (or delete) the fields that are in this contenttype, edit the file `contenttypes.yml`
#       in the folder `app/config/`, using the editor of your choice, or by going to 'Configuration' »
#       'Contenttypes' in the menu on the left.
#     fields:
#         title:
#             type: text
#             class: large
#             required: true
#             pattern: "*{2,255}" # see: http://html5pattern.com/
#             group: Text
#         slug:
#             type: slug
#             uses: [ selectfield, title ]
#         html:
#             type: html
#             height: 150px
#         textarea:
#             type: textarea
#             postfix: "<p><em>This is a plain text area. the contents will not be processed.</em></p>"
#         markdown:
#             type: markdown
#             postfix: "<p><em>This field gets parsed as <a href='https://help.github.com/articles/markdown-basics'>Markdown</a>, when rendered on the site.</em></p>"
#         geolocation:
#             type: geolocation
#             group: Media
#         video:
#             type: video
#         image:
#             type: image
#             attrib: title
#             extensions: [ gif, jpg, png ]
#         imagelist:
#             type: imagelist
#         file:
#             type: file
#             group: files
#         filelist:
#             type: filelist
#         template:
#             type: templateselect
#             filter: '*.twig'
#         checkbox:
#             type: checkbox
#             label: "This is a checkbox"
#             group: other
#         datetime:
#             type: datetime
#             default: "2000-01-01"
#         date:
#             type: date
#             default: "first day of last month"
#         integerfield:
#             type: integer
#             index: true
#         floatfield:
#             type: float
#         selectfield:
#             type: select
#             values: [ none, foo, bar ]
#         multiselect:
#             type: select
#             values: [ A-tuin, Donatello, Rafael, Leonardo, Michelangelo, Koopa, Squirtle ]
#             multiple: true
#             postfix: "Select your favourite turtle(s)."
#         selectentry:
#             type: select
#             values: entries/id,title
#             postfix: "Select an entry"
#     relations:
#         entries:
#             multiple: false
#             label: Choose an entry
#             order: -id
#             format: "{{ item.title|escape }} <span>(№ {{ item.id }})</span>"
#         pages:
#             multiple: true
#             order: title
#             label: Select zero or more pages
#     taxonomy: [ categories, tags ]
#     show_on_dashboard: true
#     default_status: publish
#     searchable: false
#     icon: cubes
#     icon_singular: cube


# possible field types:
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - Simple, plain < textarea > field, which is parsed as Markdown text.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)


# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable
