# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

cs:
  - label: Český pavilon v kostce
    title: Základní informace o pavilonu a dodavateli
    path: homepage
  - label: Prohlídka pavilonu
    title: Prohlédněte si pavilon po jednotlivých patrech
    path: page/o-pavilonu
  - label: Historie českých expo pavilonů
    title: Stručná historie českých pavilonů a jejich osudů
    path: cs/historie
  - label: Zpravodaj pavilonu
    title: Informace o aktuálním dění pavilonu
    path: cs/blog
    submenu:
      - label: vše
        path: cs/blog/
      - label: fotogalerie
        path: cs/blog/
      - label: informace partnerů
        path: cs/blog/
      - label: o pavilonu
        path: cs/blog/
      - label: rozhovory
        path: cs/blog/rozhovory

en:
  - label: Overview of Czech pavilion
    title: All the informations about pavilion and stuff
    path: homepage
  - label: Look inside the pavilion
    title: Prohlédněte si pavilon po jednotlivých patrech
    path: page/1
  - label: Blog from pavilion
    title: Informace o aktuálním dění pavilonu
    path: blog/
    submenu:
      - label: vše
        path: blog/
      - label: fotogalerie
        path: taxonomy


main:
  - label: Home
    title: This is the first menu item.
    path: homepage
    class: first
  - label: Second item
    path: entry/1
    submenu:
      - label: Sub 1
        path: entry/2
      - label: Sub 2
        class: menu-item-class
        path: entry/3
      - label: Sub 3
        path: entry/4
      - label: Sub 4
        class: sub-class
        path: page/3
  - label: All pages
    path: pages/
  - label: The Bolt site
    link: http://bolt.cm
    class: last
