# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

cs:
  - label: Český pavilon v kostce
    title: Základní informace o pavilonu a dodavateli
    path: cs/
  - label: Prohlídka pavilonu
    title: Prohlédněte si pavilon po jednotlivých patrech
    path: page/o-pavilonu
  - label: Historie českých expo pavilonů
    title: Stručná historie českých pavilonů a jejich osudů
    path: cs/historie
  - label: Zpravodaj pavilonu
    title: Informace o aktuálním dění pavilonu
    path: cs/blog
    submenu:
      - label: vše
        path: cs/blog/
      - label: fotogalerie
        path: cs/blog/kategorie/fotogalerie
      - label: informace partnerů
        path: cs/blog/
      - label: o pavilonu
        path: cs/blog/
      - label: rozhovory
        path: cs/blog/rozhovory

en:
  - label: Overview of Czech pavilion
    title: All the informations about pavilion and stuff
    path: en/
  - label: Look inside the pavilion
    title: Prohlédněte si pavilon po jednotlivých patrech
    path: page/o-pavilonu
  - label: History of czech expo pavilions
    title: Brief history in context of reuse
    path: en/historie
  - label: Blog from pavilion
    title: Recent updates from pavilion
    path: en/blog/
    submenu:
      - label: all
        path: en/blog/
      - label: photogallery
        path: en/fotogalerie/


main:
  - label: Home
    title: This is the first menu item.
    path: homepage
    class: first
  - label: Historie
    path: cs/historie
  - label: Zpravodaj
    path: cs/blog
  - label: The Bolt site
    link: http://bolt.cm
    class: last
