# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

cs:
  - label: Český pavilon v kostce
    title: Základní informace o pavilonu a dodavateli
    path: cs/
  - label: Prohlídka pavilonu
    title: Prohlédněte si pavilon po jednotlivých patrech
    path: cs/o-pavilonu
    submenu:
      - label: Schéma pater pavilonu
        path: cs/o-pavilonu
      - label: Virtuální prohlídka pavilonu
        path: cs/virtualni-prohlidka
  - label: Historie českých expo pavilonů
    title: Stručná historie českých pavilonů a jejich osudů
    path: cs/historie
  - label: Zpravodaj pavilonu
    title: Informace o aktuálním dění pavilonu
    path: cs/blog
    submenu:
      - label: vše
        path: cs/blog/
      - label: Expozice
        path: cs/kategorie/expozice
      - label: Fotogalerie
        path: cs/kategorie/fotogalerie
      - label: O pavilonu
        path: cs/kategorie/O pavilonu
#      - label: Rozhovory
#        path: cs/kategorie/rozhovory
      - label: Zprávy partnerů
        path: cs/blog/Zpravy partneru


en:
  - label: Czech Pavilion in Brief
    title: Basic information about the pavilion and its supplier
    path: en/
  - label: Tour of the Pavilion
    title: Explore individual floors of the pavilion
    path: en/o-pavilonu
    submenu:
      - label: Explore individual floors of the pavilion
        path: en/o-pavilonu
      - label: Virtual Pano tour
        path: en/virtualni-prohlidka
  - label: History of Czech EXPO Pavilions
    title: Brief history of Czech EXPO pavilions and their fate
    path: en/historie
  - label: Pavilion News
    title: Recent updates from pavilion
    path: en/blog/
    submenu:
      - label: All
        path: en/blog/
      - label: Exhibitions
        path: en/kategorie/expozice
      - label: photo gallery
        path: en/kategorie/fotogalerie
      - label: about the Pavilion
        path: en/kategorie/O pavilonu
#      - label: interviews
#        path: cs/kategorie/rozhovory
      - label: partner information
        path: en/blog/Zpravy partneru


main:
  - label: Home
    title: This is the first menu item.
    path: homepage
    class: first
  - label: Historie
    path: cs/historie
  - label: Zpravodaj
    path: cs/blog
  - label: The Bolt site
    link: http://bolt.cm
    class: last
