# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]


#Pavilon EXPO2105 taxonomy

kategorie:
    name: Kategorie
    slug: kategorie
    singular_name: Kategorie1
    singular_slug: kategorie1
    behaves_like: categories
    multiple: true
    options: { expozice: "Expozice", fotogalerie: "Fotogalerie", pavilon: "O pavilonu", rozhovory: "Rozhovory", partneri: "Zprávy partnerů" }
    listing_template: zpravodaj.twig

stitky:
    slug: stitky
    singular_slug: stitek
    behaves_like: tags
    #listing_template: tag-listing.twig #custom template

statiky:
    slug: statiky
    singular_slug: statik
    behaves_like: categories
    multiple: true
    options: { homepage: "Domácí strana", pavilon: "O pavilonu", historie: "Historie", blog: "Zpravodaj" }
    has_sortorder: true

rozcestnik:
    slug: rozcestnik
    singular_slug: ukazatel
    behaves_like: grouping
    multiple: false
    options: { o-pavilonu: "Další články o pavilonu", modularni-architektura: "Více o modulární výstavbě" }
    has_sortorder: true