# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

kategorie:
    name: Kategorie
    slug: kategorie
    singular_name: Kategorie1
    singular_slug: kategorie1
    behaves_like: categories
    multiple: true
    options: { expozice: "Expozice", partneri: "Zprávy partnerů", fotogalerie: "Fotogalerie", pavilon: "O pavilonu", rozhovory: "Rozhovory" }
    listing_template: zpravodaj.twig

stitky:
    slug: stitky
    singular_slug: stitek
    behaves_like: tags
    #listing_template: tag-listing.twig #custom template

statiky:
    slug: statiky
    singular_slug: statik
    behaves_like: grouping
    options: { homepage: "Domácí strana", pavilon: "O pavilonu", historie: "Historie", blog: "Zpravodaj" }
    has_sortorder: true

rozcestnik:
    slug: rozcestnik
    singular_slug: ukazatel
    behaves_like: grouping
    multiple: false
    options: { o-pavilonu: "Další články o pavilonu", modularni-architektura: "Více o modulární výstavbě" }
    has_sortorder: true

# tags:
#     slug: tags
#     singular_slug: tag
#     behaves_like: tags
#     #listing_template: tag-listing.twig #custom template

# chapters:
#     slug: chapters
#     singular_slug: chapter
#     behaves_like: grouping
#     options: { main: "The main chapter", meta: "Meta Chapter", other: "The other stuff" }
#     has_sortorder: true

#categories:
#    name: Categories
#    slug: categories
#    singular_name: Category
#    singular_slug: category
#    behaves_like: categories
#    multiple: true
#    options: [ news, events, movies, music, books, life, love, fun ]
